server:
  port: 8091
  servlet:
    context-path: /library-app

spring:
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
    enabled: true
  application:
    name: libraryApp
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword

  jpa:
    open-in-view: false
    database: postgresql
    hibernate:
#      ddl-auto: create
    #    show-sql: true
    properties:
      hibernate:
        format_sql: true